on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00
name: Schedule / sync-upstream of Yikf's forked repositories
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Sync kyuubi to fork repo
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: Yikf
        repo: kyuubi
        branch: master
    - name: Sync spark to fork repo
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: Yikf
        repo: spark
        branch: master
