on:
  schedule:
    - cron: "0 * * * *" # every hour
name: Schedule / sync-upstream of PorterZhang2021's forked repositories
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Sync robustmq to fork repo
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: PorterZhang2021
        repo: robustmq
        branch: main
    - name: Sync supercv-backend to fork repo
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: PorterZhang2021
        repo: supercv-backend
        branch: main
    - name: Sync supercv-frontend to fork repo
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: PorterZhang2021
        repo: supercv-frontend
        branch: main
    - name: Sync hui-rs to fork repo
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: PorterZhang2021
        repo: hudi-rs
        branch: main