on:
  push:
  pull_request_target:
    branches: [master]
name: Tests / test-sync-upstream
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Sync trino to fork repo
      uses: ./.
      with:
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        owner: Yikf
        repo: trino
        branch: master
